version: "3.3"

services:

  mysql:
    build: ./mysql/.
    container_name: "mysql"
    restart: "always"
    networks:
      - web
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: test

  adminer:
    image: adminer
    container_name: "adminer"
    restart: "always"
    networks:
      - web
    depends_on:
      - mysql

  nginx-adminer:
    build: ./nginx-adminer/.
    container_name: "nginx-adminer"
    restart: "always"
    ports:
      - "8080:80"
    networks:
      - web
    depends_on:
      - adminer

  backend:
    build: ./backend/.
    container_name: "backend"
    restart: "always"
    networks:
      - web
    working_dir: /app
    command: python3 -m gunicorn -w 4 app:app -b 0.0.0.0:8000
    depends_on:
      - mysql

  nginx-backend:
    build: ./nginx-backend/.
    container_name: "nginx-backend"
    restart: "always"
    ports:
      - "3000:80"
    networks:
      - web
    depends_on:
      - backend

  frontend:
    build: ./frontend/.
    container_name: "frontend"
    restart: "always"
    networks:
      - web
    environment:
      NODE_ENV: production
    working_dir: /app
    command: npx serve build
    depends_on:
      - backend

  nginx-frontend:
    build: ./nginx-frontend/.
    container_name: "nginx-frontend"
    restart: "always"
    ports:
      - "80:80"
    networks:
      - web
    depends_on:
      - frontend

networks:
  web: